### ISSUE TITLE
No export in path.d.ts

### ISSUE THREAD

**Issue by bertvh** [joemaddalone/path#16]
When I just `import Path from '@joemaddalone/path';`, I get `...path.d.ts is not a module`. I don't know a lot about d.ts files but I suspect an export maybe missing. When I add the following to the d.ts file:

```
export default Path;
```

everything works nicely. I've tried to fiddle with jsdoc to output this but didn't really succeed.

Using this in a SvelteKit app. Not sure if this is a general issue.

**Comment by joemaddalone** [comment]
@bertvh thanks for catching this. I added a fix to 1.2.10, and I specifically tested it in a SvelteKit app.

Updating to that version should resolve the issue for you.

**Comment by bertvh** [comment]
Tried it. Works! 🥳 Thanks al lot!
